### ISSUE TITLE
WARN: Unexpected exception while running analysis

### ISSUE THREAD

**Issue by cmenzi** [gretard/sonar-ps-plugin#2]
Hi

When running the analysis I get the following warning after analysis:

```
WARN: Unexpected exception while running analysis
javax.xml.bind.UnmarshalException: null
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189)
	at org.sonar.plugins.powershell.ScriptAnalyzerSensor.execute(ScriptAnalyzerSensor.java:72)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: org.xml.sax.SAXParseException: Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1472)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1014)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	... 38 common frames omitted
```

What are we doing wrong?

**Comment by gretard** [comment]
Hello,

Thank you for raising issue. Could you provide more details? Do you have PSScriptAnalyzer analyzer installed on the machine on which you are trying to run analysis?  Which SonarQube's runner are you using? :)

**Comment by cmenzi** [comment]
Hi

* Yes, PSScriptAnalyzer is installed and works. It's just the Tokenizer I think
* `sonar-scanner-3.1.0.1141`

```
INFO: SonarQube Scanner 3.1.0.1141
INFO: Java 1.8.0_162 Oracle Corporation (64-bit)
INFO: Windows Server 2016 10.0 amd64
INFO: User cache: C:\Users\ContainerAdministrator\.sonar\cache
INFO: SonarQube server 6.7.3
INFO: Default locale: "en_US", source code encoding: "UTF-8"
```

```
INFO: Quality profile for ps: Sonar Way
INFO: Sensor ScriptAnalyzerSensor [ps]
INFO: Starting running powershell analysis: (Invoke-ScriptAnalyzer -Path 'C:\glr\b\9e7218d1\0\iot-environment\azure-recipes' -Recurse | Select-Object RuleName, Message, Line, Column, Severity, @{Name='File';Expression={$_.Extent.File }} | ConvertTo-Xml).Save('C:\glr\b\9e7218d1\0\iot-environment\azure-recipes\.scannerwork\.sonartmp\7431552642098919773.tmp')
INFO: Finished running powershell analysis
WARN: Unexpected exception while running analysis
... StackTrace from above.
``

**Comment by gretard** [comment]
Hi,

Thank you for your reply. Which PowerShell version are you using?  I would like to try to reproduce the issue. :)

**Comment by ktraister** [comment]
Hate to Necrobump, but I'm getting this error as well. I'm on PowerShell 5.1 and plugin version 0.3.0 built from the master branch of this repo

**Comment by gretard** [comment]
Thank you,  for raising this. Will take a look this into soon.

**Comment by ktraister** [comment]
I did some troubleshooting on this today, but only enough to find that the file I was trying to read had been created. I was having trouble reading from the file (Java is a new language for me), so I'm not sure if my code was bad or I was just reading an empty file.

**Comment by gretard** [comment]
Hi,

I think it was just an empty file. Could you provide more details? What OS
have you been using? Did the analysis finish? Also, did you check if in
SonarQube project is shown ?

**Comment by ktraister** [comment]
This is a Windows 10 Jenkins build slave that we're using for analysis. The analysis finished successfully, and the SonarQube project shows that code was scanned, but nothing was found. 

We've had some previous weirdness with PS in this Windows slave, mostly because we have 5.1 and 6 installed, and depending on how we call PS we can get either. Don't beat your head against the code too hard, I'm starting to think there's an issue with the PS install on the build slave. I'll do some digging on this today.

**Comment by ktraister** [comment]
Looks like we're on PowerShell 5.1, and after making sure the plugin is installed I'm still getting the same behavior

**Comment by gretard** [comment]
Hi, I would suggest trying on build machine to run PSScriptAnalyzer manually by using command: 

> Invoke-ScriptAnalyzer -Path 'C:\glr\b\9e7218d1\0\x\y' -Recurse

to verify that it works and anything is found. If anything is found, then maybe you could run Sonarqube plugin with Debug (-X option) mode enabled and maybe attach it here?

**Comment by ktraister** [comment]
<img width="856" alt="screen shot 2018-09-24 at 2 10 56 pm" src="https://user-images.githubusercontent.com/31903117/45970115-b17d1680-c003-11e8-883c-39326a8ee6e9.png">

When I ran the command as you posted it, It fell on it's face. Running it with the correct path produced the correct output

**Comment by gretard** [comment]
Hi, thank you for output.  I did some changes how files are handled. Could you try running analysis with [0.3.1 plugin version](https://github.com/gretard/sonar-ps-plugin/releases/tag/0.3.1) version?

**Comment by ktraister** [comment]
No dice, still seeing the error. 0.3.1 output:

```
17:49:25.595 INFO: Quality profile for ps: Sonar Way
17:49:26.486 DEBUG: 'Generic Coverage Report' skipped because one of the required properties is missing
17:49:26.486 DEBUG: 'Generic Test Executions Report' skipped because one of the required properties is missing
17:49:26.497 DEBUG: 'C#' skipped because there is no related file in current project
17:49:26.499 DEBUG: 'C# Properties' skipped because there is no related file in current project
17:49:26.501 DEBUG: 'C# Tests Coverage Report Import' skipped because there is no related file in current project
17:49:26.501 DEBUG: '[Deprecated] C# Integration Tests Coverage Report Import' skipped because there is no related file in current project
17:49:26.504 DEBUG: 'C# Unit Test Results Import' skipped because there is no related file in current project
17:49:26.504 DEBUG: 'Python Squid Sensor' skipped because there is no related file in current project
17:49:26.505 DEBUG: 'PylintSensor' skipped because there is no related file in current project
17:49:26.506 DEBUG: 'PylintImportSensor' skipped because there is no related file in current project
17:49:26.506 DEBUG: 'PythonXUnitSensor' skipped because there is no related file in current project
17:49:26.508 DEBUG: 'SurefireSensor' skipped because there is no related file in current project
17:49:26.509 DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
17:49:26.513 DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
17:49:26.513 DEBUG: 'Flex' skipped because there is no related file in current project
17:49:26.513 DEBUG: 'Flex Cobertura' skipped because there is no related file in current project
17:49:26.514 DEBUG: 'XML Sensor' skipped because there is no related file in current project
17:49:26.514 DEBUG: 'PHP sensor' skipped because there is no related file in current project
17:49:26.515 DEBUG: 'Analyzer for "php.ini" files' skipped because there is no related file in current project
17:49:26.515 DEBUG: 'SonarTS' skipped because there is no related file in current project
17:49:26.515 DEBUG: 'SonarTS Coverage' skipped because there is no related file in current project
17:49:26.515 DEBUG: 'SonarJS' skipped because there is no related file in current project
17:49:26.515 DEBUG: 'SonarJS Coverage' skipped because there is no related file in current project
17:49:26.517 DEBUG: 'Generic Coverage Report' skipped because one of the required properties is missing
17:49:26.517 DEBUG: 'Generic Test Executions Report' skipped because one of the required properties is missing
17:49:26.518 DEBUG: 'C#' skipped because there is no related file in current project
17:49:26.519 DEBUG: 'C# Properties' skipped because there is no related file in current project
17:49:26.519 DEBUG: 'C# Tests Coverage Report Import' skipped because there is no related file in current project
17:49:26.519 DEBUG: '[Deprecated] C# Integration Tests Coverage Report Import' skipped because there is no related file in current project
17:49:26.520 DEBUG: 'C# Unit Test Results Import' skipped because there is no related file in current project
17:49:26.520 DEBUG: 'Python Squid Sensor' skipped because there is no related file in current project
17:49:26.520 DEBUG: 'PylintSensor' skipped because there is no related file in current project
17:49:26.520 DEBUG: 'PylintImportSensor' skipped because there is no related file in current project
17:49:26.520 DEBUG: 'PythonXUnitSensor' skipped because there is no related file in current project
17:49:26.520 DEBUG: 'SurefireSensor' skipped because there is no related file in current project
17:49:26.520 DEBUG: 'JaCoCoSensor' skipped because there is no related file in current project
17:49:26.520 DEBUG: 'JavaSquidSensor' skipped because there is no related file in current project
17:49:26.523 DEBUG: 'Flex' skipped because there is no related file in current project
17:49:26.523 DEBUG: 'Flex Cobertura' skipped because there is no related file in current project
17:49:26.524 DEBUG: 'XML Sensor' skipped because there is no related file in current project
17:49:26.524 DEBUG: 'PHP sensor' skipped because there is no related file in current project
17:49:26.524 DEBUG: 'Analyzer for "php.ini" files' skipped because there is no related file in current project
17:49:26.524 DEBUG: 'SonarTS' skipped because there is no related file in current project
17:49:26.524 DEBUG: 'SonarTS Coverage' skipped because there is no related file in current project
17:49:26.524 DEBUG: 'SonarJS' skipped because there is no related file in current project
17:49:26.524 DEBUG: 'SonarJS Coverage' skipped because there is no related file in current project
17:49:26.528 DEBUG: Sensors : ScriptAnalyzerSensor -> TokenizerSensor -> SonarJavaXmlFileSensor -> Zero Coverage Sensor -> CPD Block Indexer
17:49:26.528 INFO: Sensor ScriptAnalyzerSensor [ps]
17:49:26.536 INFO: Starting Script-Analyzer using powershell: [powershell.exe, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\ps6333045538181498298scriptAnalyzer.ps1, -inputDir, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test, -output, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\8836023087676428316.tmp]
17:49:26.918 WARN: Unexpected exception while running analysis
javax.xml.bind.UnmarshalException: null
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(Unknown Source)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(Unknown Source)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(Unknown Source)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(Unknown Source)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(Unknown Source)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(Unknown Source)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(Unknown Source)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(Unknown Source)
	at org.sonar.plugins.powershell.sensors.ScriptAnalyzerSensor.execute(ScriptAnalyzerSensor.java:84)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:302)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:297)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:271)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: org.xml.sax.SAXParseException: Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	... 39 common frames omitted

17:49:26.918 INFO: Sensor ScriptAnalyzerSensor [ps] (done) | time=390ms
17:49:26.918 INFO: Sensor TokenizerSensor [ps]
17:49:26.922 DEBUG: Running [powershell.exe, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\ps7514036744813990746parser.ps1, -inputFile, 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Examples\Example-Install.ps1', -output, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\899398494356469705.tmp] command
17:49:27.365 DEBUG: 'Examples/Example-Install.ps1' generated metadata  with charset 'windows-1252'
17:49:27.387 DEBUG: Running analysis for 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Examples\Example-Install.ps1' to C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\899398494356469705.tmp finished.
17:49:27.388 DEBUG: Running [powershell.exe, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\ps7514036744813990746parser.ps1, -inputFile, 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Examples\Example-Main.ps1', -output, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\7254444625773892954.tmp] command
17:49:27.817 DEBUG: 'Examples/Example-Main.ps1' generated metadata  with charset 'windows-1252'
17:49:27.826 DEBUG: Running analysis for 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Examples\Example-Main.ps1' to C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\7254444625773892954.tmp finished.
17:49:27.827 DEBUG: Running [powershell.exe, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\ps7514036744813990746parser.ps1, -inputFile, 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Examples\Example-Sync.ps1', -output, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\6921931155492085344.tmp] command
17:49:28.245 DEBUG: 'Examples/Example-Sync.ps1' generated metadata  with charset 'windows-1252'
17:49:28.247 DEBUG: Running analysis for 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Examples\Example-Sync.ps1' to C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\6921931155492085344.tmp finished.
17:49:28.248 DEBUG: Running [powershell.exe, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\ps7514036744813990746parser.ps1, -inputFile, 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Functions\Private\Format-XML.ps1', -output, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\2114092139466042167.tmp] command
17:49:28.678 DEBUG: 'Functions/Private/Format-XML.ps1' generated metadata  with charset 'windows-1252'
17:49:28.685 DEBUG: Running analysis for 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Functions\Private\Format-XML.ps1' to C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\2114092139466042167.tmp finished.
17:49:28.686 DEBUG: Running [powershell.exe, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\ps7514036744813990746parser.ps1, -inputFile, 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Functions\Private\Get-HabBind.ps1', -output, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\2432284979142228371.tmp] command
17:49:29.128 DEBUG: 'Functions/Private/Get-HabBind.ps1' generated metadata  with charset 'windows-1252'
17:49:29.136 DEBUG: Running analysis for 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Functions\Private\Get-HabBind.ps1' to C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\2432284979142228371.tmp finished.
17:49:29.137 DEBUG: Running [powershell.exe, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\ps7514036744813990746parser.ps1, -inputFile, 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Functions\Private\Get-HabPackageParam.ps1', -output, C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\4138711521827726583.tmp] command
17:49:29.545 DEBUG: 'Functions/Private/Get-HabPackageParam.ps1' generated metadata  with charset 'windows-1252'
17:49:29.552 DEBUG: Running analysis for 'C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\Functions\Private\Get-HabPackageParam.ps1' to C:\hab\svc\jenkins-slave\data\workspace\workspace\sonar_test\.scannerwork\.sonartmp\4138711521827726583.tmp finished.
```

**Comment by gretard** [comment]
Hi, I managed to reproduce the issue with Powershell 6 version. I would suggest trying to update PSScript analyzer and Powershell if you are using Powershell 6 version. Also, I have updated 0.3.1 version jar with some additional logging. Could you reinstall that and run with -X option to see what kind of error/output is generated by the plugin? :)

**Comment by ktraister** [comment]
It seems that we're having an issue with PS6 on our build slaves right now, I'm working on fixing that. Now we're getting powershell errors that mean something instead of stack traces, which is really helpful! Nice feature! 

Once I have the PS6 issues straitened out, I'll comment here

**Comment by gretard** [comment]
I would suggest updating Powershell version to the latest :)

**Comment by ktraister** [comment]
🥇
