### ISSUE TITLE
Rule missing

### ISSUE THREAD

**Issue by nikhiljainonline** [gretard/sonar-ps-plugin#3]
Hi 
When I run the analysis from VSTS, most of it works fine but I get an error saying - 

The rule 'ps-psanalyzer:PSAvoidTrailingWhitespace' does not exist.

Seems like this rule is missing in the sonarqube.

Thanks
Nikhil

**Comment by gretard** [comment]
Thank you for raising the issue. I will check the rules :)

**Comment by gretard** [comment]
Hi, please check the latest release of the plugin (https://github.com/gretard/sonar-ps-plugin/releases/tag/0.2.2). Now this should be fixed.

**Comment by nikhiljainonline** [comment]
Thanks. This issue is fixed. I don't get those errors anymore. But I am getting a error which was there before also (log below) - 

INFO: Starting running powershell analysis: (Invoke-ScriptAnalyzer -Path 'E:\Agents\1\_work\272\s' -Recurse | Select-Object RuleName, Message, Line, Column, Severity, @{Name='File';Expression={$_.Extent.File }} | ConvertTo-Xml).Save('E:\Agents\1\_work\272\s\.scannerwork\.sonartmp\8506456086635953788.tmp')
INFO: Finished running powershell analysis
DEBUG: 'Raet.DACPAC/XLDeployDeploymentScript.ps1' generated metadata  with charset 'windows-1252'
WARN: Unexpected exception while adding issue
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at java.lang.Integer.parseInt(Unknown Source)
	at org.sonar.plugins.powershell.ScriptAnalyzerSensor.execute(ScriptAnalyzerSensor.java:81)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:88)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:82)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:68)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:88)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:180)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:288)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:283)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:261)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:48)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:84)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:121)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:121)
	at org.sonar.batch.bootstrapper.Batch.doExecuteTask(Batch.java:116)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:71)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:171)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:128)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:111)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)

**Comment by gretard** [comment]
Thank you for raising this. Will take a look :)

**Comment by gretard** [comment]
Hi, please take a look at latest plugin version [0.3.0 version](https://github.com/gretard/sonar-ps-plugin/releases/tag/0.3.0) the last issue should be gone now :) Please, let me know if that's not the case.
